/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface ScreenHome {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLScreenHomeElement extends Components.ScreenHome, HTMLStencilElement {
    }
    var HTMLScreenHomeElement: {
        prototype: HTMLScreenHomeElement;
        new (): HTMLScreenHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "screen-home": HTMLScreenHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ScreenHome {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "screen-home": ScreenHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "screen-home": LocalJSX.ScreenHome & JSXBase.HTMLAttributes<HTMLScreenHomeElement>;
        }
    }
}
